apiVersion: v1
kind: Service
metadata:
  name: __REPO_NAME__
  namespace: fe-prod
  labels:
    app: __REPO_NAME__ # 追踪哪一个pod需要暴露端口
spec:
  ports:
    - name: http
      port: 8080 # svc服务端口
      protocol: TCP
      targetPort: 8080 # 容器端口
  sessionAffinity: None
  selector:
    app: __REPO_NAME__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __REPO_NAME__
  namespace: fe-prod
  labels:
    app: __REPO_NAME__
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: __REPO_NAME__
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: __REPO_NAME__
    spec:
      containers:
        - image: 'reg.redrock.team/fe-prod-artifacts/__REPO_NAME__:__HASH__'
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
          - name: CLUSTER
            value: CQUPT
          - name: DOMAIN
            value: fe-prod.redrock.cqupt.edu.cn
          lifecycle: {}
          name: __REPO_NAME__
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: reg.redrock.team
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seLinuxOptions: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-__REPO_NAME__
  namespace: fe-prod
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /__REPO_NAME__
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: __REPO_NAME__
  namespace: fe-prod
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`fe-prod.redrock.cqupt.edu.cn`) && PathPrefix(`/__REPO_NAME__`)
    middlewares:
    - name: stripprefix-__REPO_NAME__
    - name: cors
    kind: Rule
    services:
      - name: __REPO_NAME__
        port: 8080