apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"26"},"labels":{"app":"redrock-house"},"name":"redrock-house","namespace":"fe-prod"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"redrock-house"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"redrock-house"}},"spec":{"containers":[{"env":[{"name":"CLUSTER","value":"CQUPT"},{"name":"DOMAIN","value":"fe-prod.redrock.cqupt.edu.cn"}],"image":"ccr.ccs.tencentyun.com/redrock/fe-prod-artifacts:redrock-house-13c3e4353294a02ade50da1ac4f426b7697c3004","imagePullPolicy":"Always","name":"redrock-house","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"ccr.ccs.tencentyun.com"}],"restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2022-02-28T12:07:29Z"
  generation: 2
  labels:
    app: redrock-house
  name: redrock-house
  namespace: fe-prod
  resourceVersion: "39477084"
  uid: fa2db1bd-ae38-444c-aaec-cc37c9f52eb3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redrock-house
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redrock-house
    spec:
      containers:
      - env:
        - name: CLUSTER
          value: CQUPT
        - name: DOMAIN
          value: fe-prod.redrock.cqupt.edu.cn
        image: ccr.ccs.tencentyun.com/redrock/fe-prod-artifacts:redrock-house-13c3e4353294a02ade50da1ac4f426b7697c300d
        imagePullPolicy: Always
        name: redrock-house
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ccr.ccs.tencentyun.com
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-28T12:11:50Z"
    lastUpdateTime: "2022-02-28T12:11:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-28T12:07:30Z"
    lastUpdateTime: "2022-03-05T14:07:30Z"
    message: ReplicaSet "redrock-house-f556687d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1